import 'package:relapse_flutter/data/remote/patient_remote_source.dart';
import 'package:relapse_flutter/data/remote/watch_remote_source.dart';
import 'package:relapse_flutter/models/pairing_info.dart';
import 'package:relapse_flutter/models/patient.dart';
import 'package:relapse_flutter/models/watch_status.dart';

/// Service managing watch pairing flow and status monitoring.
///
/// Operates through Firestore — the watch writes its status and pairing
/// responses there, and this service listens for changes.
abstract class WatchCommunicationService {
  /// Submit a pairing code generated by the watch app and claim it.
  /// Returns the watchId associated with the code.
  Future<String> submitPairingCode(String uid, String code);

  /// Stream pairing info to detect when the watch pairs.
  Stream<PairingInfo?> watchPairingStatus(String uid);

  /// Complete pairing by creating the patient record.
  Future<Patient> completePairing({
    required String uid,
    required String name,
    int? age,
    String? notes,
    required String watchId,
  });

  /// Unpair the watch and clean up.
  Future<void> unpairWatch(String uid);

  /// Finalize pairing after patient profile setup is complete.
  Future<void> finalizePairing(String uid, {required String patientName, required String patientId});

  /// Push updated patient info so the watch picks up edits.
  Future<void> updatePatientInfo(String uid, {required String patientName, String? patientId});

  /// Stream watch connectivity and battery status.
  Stream<WatchStatus?> watchStatus(String uid, String patientId);
}

class FirebaseWatchCommunicationService implements WatchCommunicationService {
  final WatchRemoteSource _watchSource;
  final PatientRemoteSource _patientSource;

  FirebaseWatchCommunicationService({
    required WatchRemoteSource watchSource,
    required PatientRemoteSource patientSource,
  })  : _watchSource = watchSource,
        _patientSource = patientSource;

  @override
  Future<String> submitPairingCode(String uid, String code) async {
    return await _watchSource.claimPairingCode(uid, code);
  }

  @override
  Stream<PairingInfo?> watchPairingStatus(String uid) {
    return _watchSource.watchPairingInfo(uid);
  }

  @override
  Future<Patient> completePairing({
    required String uid,
    required String name,
    int? age,
    String? notes,
    required String watchId,
  }) async {
    final patient = Patient(
      id: '', // will be set by Firestore
      caregiverUid: uid,
      name: name,
      age: age,
      notes: notes,
      pairedWatchId: watchId,
      createdAt: DateTime.now(),
    );
    await _patientSource.savePatient(uid, patient);
    return patient;
  }

  @override
  Future<void> unpairWatch(String uid) async {
    await _watchSource.unpairWatch(uid);
  }

  @override
  Future<void> finalizePairing(String uid, {required String patientName, required String patientId}) async {
    await _watchSource.finalizePairing(uid, patientName: patientName, patientId: patientId);
  }

  @override
  Future<void> updatePatientInfo(String uid, {required String patientName, String? patientId}) async {
    await _watchSource.updatePatientInfo(uid, patientName: patientName, patientId: patientId);
  }

  @override
  Stream<WatchStatus?> watchStatus(String uid, String patientId) {
    return _watchSource.watchWatchStatus(uid, patientId);
  }
}
